name: build-test
on:
  push:
    # branches: [ master ]
    paths-ignore:
    - '**/*.gitattributes'
    - '**/*.gitignore'
    - '**/*.md'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    outputs:
      dotnet-version: ${{steps.get-version.outputs.dotnet-version}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get dotnet-version
        id: get-version
        shell: pwsh
        run: ./get-version.ps1

      - name: Print dotnet-version
        shell: pwsh
        run: Write-Output "${{steps.get-version.outputs.dotnet-version}}"

      - name: Dotnet Install
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "${{steps.get-version.outputs.dotnet-version}}"

      - name: Build, Test and Publish
        shell: pwsh
        run: ./build.ps1 -$Project:test/CarManager.UnitTests/CarManager.UnitTests.csproj


