name: build-test
on:
  push:
    # branches: [ master ]
    paths-ignore:
    - '**/*.gitattributes'
    - '**/*.gitignore'
    - '**/*.md'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    services:
      localstack:
        image: localstack/localstack:2.1.0
        ports:
          - 4566:4566
        env:
          SERVICES: dynamodb,sns,sqs,s3
    name: build
    runs-on: ubuntu-latest
    outputs:
      dotnet-version: ${{steps.get-version.outputs.dotnet-version}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get dotnet-version
        id: get-version
        shell: pwsh
        run: ./get-version.ps1

      - name: Print dotnet-version
        shell: pwsh
        run: Write-Output "${{steps.get-version.outputs.dotnet-version}}"

      - name: Dotnet Install
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "${{steps.get-version.outputs.dotnet-version}}"

      - name: Run Unit Tests
        shell: pwsh
        run: ./test.ps1 -Project:./test/CarManager.UnitTests/CarManager.UnitTests.csproj

      # - name: Run Integration Tests
      #   shell: pwsh
      #   run: ./test.ps1 -Project:./test/CarManager.IntegrationTests/CarManager.IntegrationTests.csproj

      - name: Build and Publish
        shell: pwsh
        run: ./publish.ps1 -Project:./src/CarManager/CarManager.csproj

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: publish
          path: |
            publish



